CREATE DATABASE LA_FITNESS;

USE LA_FITNESS;

CREATE TABLE Members(
MemberID INT PRIMARY KEY AUTO_INCREMENT,
MemberName VARCHAR(100) NOT NULL,
MemberPhone VARCHAR(15) NOT NULL UNIQUE,
MemberAddress VARCHAR(255)
);

ALTER TABLE Members
ADD COLUMN MemberEmail VARCHAR(100);


CREATE TABLE WorkoutSession(
SessionID INT PRIMARY KEY AUTO_INCREMENT,
MemberID INT NOT NULL,
MemberNAME VARCHAR(100) NOT NULL,
MemberPHONE VARCHAR(15),
SessionDate DATE NOT NULL,
WorkoutType VARCHAR(50) NOT NULL,
Duration INT NOT NULL
);

ALTER USER 'root'@'localhost' IDENTIFIED BY 'lolol';
FLUSH PRIVILEGES;

ALTER TABLE `la_fitness`.`workoutsession` 
CHANGE COLUMN `MemberID` `MemberID` INT NULL ,
CHANGE COLUMN `MemberNAME` `MemberNAME` VARCHAR(255)  NULL ,
CHANGE COLUMN `MemberPHONE` `MemberPHONE` VARCHAR(15) NULL ;

ALTER TABLE WorkoutSession
DROP COLUMN MemberNAME,
DROP COLUMN MemberPHONE;

ALTER TABLE WorkoutSession
ADD CONSTRAINT fk_member
FOREIGN KEY (MemberID) REFERENCES Members(MemberID)
ON DELETE CASCADE
ON UPDATE CASCADE;

